# Command line arguments
debug: false
overfit: false
sample_only: true
auto: true


# Task configs 
auto_step: 20 # number of autoregressive steps for sampling
task_name: 'SR' # super resolution or SO for sparse observation
SR_ratio: 8 # super resolution ratio
SO_ratio: 0.015625 # sparse observation ratio
noise_type: 'gaussian'
noise_sigma: 0.05



# Datasets & Checkpoints
dataset: 'qgv1'
home: './tmp_images/'
data_fname: '/scratch/qingqu_root/qingqu/jiayx/FlowDAS/QG/data/qg_v1/qg_full_test.pt'
load_path: '/scratch/qingqu_root/qingqu/jiayx/FlowDAS/QG/ckpts/qg_v1/best.pt'
lo_size: 128
hi_size: 128
time_lag: 2
subsampling_ratio: 1
C: 1 # number of dataset channels
num_classes: 1




# FlowDAS
sigma_coef: 1.0
beta_fn: t^2
MC_times: 25




# Model
unet_channels: 128
unet_dim_mults: [1, 2, 2, 2]
unet_resnet_block_groups: 8
unet_learned_sinusoidal_dim: 32
unet_attn_dim_head: 64
unet_attn_heads: 4
unet_learned_sinusoidal_cond: true
unet_random_fourier_features: false



# Training and Sampling
batch_size: 64
max_steps: 100000
base_lr: 0.0002
EM_sample_steps: 500
val_ratio: 0.05
validate_every: 20
sampling_batch_size: 1


# Logging
sample_every: 100
print_loss_every: 10
save_every: 100
ckpt_dir: './ckpts_qg_full' # for saving ckpts

use_wandb: true
wandb_project: 'qgv1_sampling'
wandb_entity: 'jiayx18-university-of-michigan'



# Other
num_workers: 4
device: 'cuda:0'

